### ISSUE TITLE
folder2ram -mountall fails with error: chmod: fehlender Operand + chown: fehlender Operand

### ISSUE THREAD

**Issue by 74cmonty** [bobafetthotmail/folder2ram#11]
After creating config file with 
`folder2ram -configure`
I want to mount all folders in the config file.

However I get this errors:
`
root@ld4464:/home/folder2ram# folder2ram -mountall
will now start all mountpoints
chmod: fehlender Operand
„chmod --help“ liefert weitere Informationen.
chown: fehlender Operand
„chown --help“ liefert weitere Informationen.
umount: /var/log: not mounted
umount: /var/folder2ram/var/log: not mounted
chmod: fehlender Operand
„chmod --help“ liefert weitere Informationen.
chown: fehlender Operand
„chown --help“ liefert weitere Informationen.
umount: /var/spool: not mounted
umount: /var/folder2ram/var/spool: not mounted
chmod: fehlender Operand
„chmod --help“ liefert weitere Informationen.
chown: fehlender Operand
„chown --help“ liefert weitere Informationen.
umount: /var/tmp: not mounted
umount: /var/folder2ram/var/tmp: not mounted
`

How can I fix this?

**Comment by bobafetthotmail** [comment]
That's weird, I just tried here and I got that error, but doing a second time

**folder2ram -mountall**

works fine and things are mounted correctly.

And I can't reproduce the error again, all times I mount or unmount the folders it works correctly.

Does that work for you too?

**Comment by 74cmonty** [comment]
True.
Executing `folder2ram -mountall` second time work w/o issues.
