### ISSUE TITLE
May I use multiple configuration files?

### ISSUE THREAD

**Issue by libook** [bobafetthotmail/folder2ram#18]
/etc/folder2ram/folder2ram.conf is used by openmediavault and noticed me "Do not edit this file, your changes will get lost."

So may I just create a new configuration file (for example somedir.conf) in /etc/folder2ram/ ?

**Comment by ryecoaaron** [comment]
The only time the plugin writes the config file is when the plugin is installed.  You can change the normal config file.

**Comment by bobafetthotmail** [comment]
folder2ram does not support multiple config files. Although as said above the OMV plugin is only writing the config on install so you can add things to that config file.
As it is now, this package or the OMV plugin aren't going to change much if at all in the future.
