### ISSUE TITLE
Double pipe problem

### ISSUE THREAD

**Issue by mwehr** [bobafetthotmail/folder2ram#3]
Hi,

First of all THX for this cool script!
I've found a slight mistake.
At line 280 in the folder2ram script there is a double pipe at the end which prevents the cleaner script to execute properly.
```bash
...'NR == line {print $2}' | | sed 's:/*$::' )
```
Maybe you would like check that.

regards
Mario

**Comment by bobafetthotmail** [comment]
Thanks Mario!

It's fixed now. Closing.
