### ISSUE TITLE
compatibility with zram

### ISSUE THREAD

**Issue by gilbrotheraway** [bobafetthotmail/folder2ram#37]
how can you use this with zram? i heard they both try moving the same files... I'd still like to use zram for compression only

**Comment by bobafetthotmail** [comment]
afaik zram does not move files, it just creates a compressed block device in RAM.
It's most commonly used to create a "compressed swap file in RAM" for devices with low amounts of RAM, it can't be used to store files.

So they should not interfere with each other (besides using RAM space each for their own purposes).

Maybe you mean a specific script or software that uses zram? If you tell me the name I can take a look

**Comment by ryecoaaron** [comment]
I think the request here is really to compress what folder2ram is putting in ram.  zram can create block devices that could be formatted.

**Comment by gilbrotheraway** [comment]
i meant the /tmp mount that zram-config generates for temp files, that was conflicting with the OMV flasmemory plugin but i disabled the /tmp.in zram

**Comment by bobafetthotmail** [comment]
I had a quick look at zram-config https://github.com/ecdye/zram-config and it is neat. It has the same design goals of folder2ram but is using a different (and imho better) way to achieve them that uses less RAM. It is using an OverlayFS so it does not need to copy existing files to RAM on boot, and is using a zram device to compress the files in ram. It can also sync the files from ram to disk and when this happens it should free the ram space.

I'm not sure about the compatibility issues with other system services, I had to troubleshoot quite a bit to get a systemd service or init script that does not break things by starting folder2ram at the right moment or force a logrotate so it does not interefere with logging.

Anyway zram-config is doing the same thing folder2ram also does (move a folder to ram), so each folder must be handled by either folder2ram OR zram-config.

@ryecoaaron I'm not in a position where I have time or need to add features or rework folder2ram to be more like zram-config. I will only fix issues or test and merge PRs if someone sends them. 
If you feel like you need better features or less RAM usage than what folder2ram can provide, feel free to migrate the Flashmemory plugin to use zram-config instead. From what I've seen it seems to be a drop-in replacement, as long as you test that its startup with systemd service does not break other system services as folder2ram did (see the closed bug reports on both this repo and your flashmemory plugin)
