### ISSUE TITLE
Fix for systemd umount call problem on reboot, shutdown.

### ISSUE THREAD

**Issue by mwehr** [bobafetthotmail/folder2ram#4]
Hi,

For some reason the current systemd config doesn't trigger the 
```bash
ExecStop=/sbin/folder2ram -umountall
```
on reboot or shutdown.

What works for me is:
```bash
[Unit]
Description=folder2ram systemd service

[Service]
Type=oneshot
ExecStart=/sbin/folder2ram -mountall
ExecStop=/sbin/folder2ram -umountall
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
OS is Debian 8

regards,

Mario

**Comment by bobafetthotmail** [comment]
The issue is caused by the "DefaultDependencies=No" as that is a much more advanced option I should have not included.

The After and Before options must stay, as they are there to ensure that folder2ram is called as early as possible, when no program is initialized at all.

Anyway, fixed.
