### ISSUE TITLE
World-writeble permissions

### ISSUE THREAD

**Issue by jorlandobr** [bobafetthotmail/folder2ram#6]
Looking the logs I found that warning;

Oct 12 22:45:43 ubuntu systemd[1]: Configuration file /lib/systemd/system/folder2ram_startup.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.

Oct 12 22:45:43 ubuntu systemd[1]: Configuration file /lib/systemd/system/folder2ram_shutdown.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.

**Comment by bobafetthotmail** [comment]
Thanks for feedback! 

Sounds easy enough to fix. I'll do that this weekend.

**Comment by bobafetthotmail** [comment]
just pushed an update that should fix this (and remove some debug logspam), I've tested on my system and it seems ok.

If you confirm it's ok I can close this issue.

**Comment by jorlandobr** [comment]
I am using your program as part of the OMV's plugin flashmemory. I just need to update the binary executable?

**Comment by bobafetthotmail** [comment]
yes, update only the /sbin/folder2ram file, and then to re-generate systemd servce files write on terminal 

**sudo folder2ram -enablesystemd**

(or without sudo if you are already logged as root)

Systemd might complain saying that the service is already enabled, you can ignore that.

OMV should eventually package and ship the newer version of this in a package update.

**Comment by jorlandobr** [comment]
Just checked and everything is ok now!

**Comment by bobafetthotmail** [comment]
good, thanks. Closing.
